apiVersion: v1
kind: Secret
metadata:
  name: telegram-archiver-secrets
  namespace: telegram-archiver
  labels:
    app.kubernetes.io/name: telegram-archiver
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values (replace with your actual base64 encoded values)
  # Use: echo -n "your-value" | base64
  telegram-api-id: MTIzNDU2Nzg=  # Замените на ваш API ID в base64
  telegram-api-hash: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=  # Замените на ваш API Hash в base64
  telegram-phone-number: KzEyMzQ1Njc4OTA=  # Замените на ваш номер телефона в base64
  telegram-bot-token: MTIzNDU2Nzg5MDpBQUhsZU00enU2WWZGQURJaUl0X2x3REJnTlA2SUNaWi1LVQ==  # Замените на токен бота в base64
  telegram-admin-user-id: MTIzNDU2Nzg5  # Замените на ID администратора в base64
  telegram-target-chat: QG15Y2hhbm5lbA==  # Замените на целевой чат в base64
  encryption-key: eW91ci0zMi1jaGFyYWN0ZXItZW5jcnlwdGlvbi1rZXk=  # 32-символьный ключ шифрования в base64